apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subject-access-reviewer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subject-access-reviewer
    spec:
      containers:
        - name: hug-apiserver
          image: [image]:[tag]
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: subject-access-reviewer
  labels:
    app: subject-access-reviewer
spec:
  ports:
  - port: 8000
  selector:
    app: subject-access-reviewer
